//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medi2020.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class visit
    {
        public int Id { get; set; }
        public System.DateTime Idopont { get; set; }
        public string BetegTaj { get; set; }
        public int OrvosId { get; set; }
        public int SzolgaltatasId { get; set; }
    
        public virtual doctor doctor { get; set; }
        public virtual patient patient { get; set; }
        public virtual service service { get; set; }
    }
}
